[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"

# Redirect rule to handle direct navigation to routes in SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
